import type {
  ActivityItem,
  Agent,
  CronJob,
  DocumentRecord,
  IntegrationRecord,
  Project,
  SystemInfo,
  Task,
} from "@/shared/types/models";

export const mockAgents: Agent[] = [
  {
    id: "atlas",
    name: "Atlas",
    role: "Mission Lead",
    status: "online",
    color: "#4dd4ac",
    avatar_url: null,
    workload: 74,
    throughput: 132,
    accuracy: 98,
    projects_count: 4,
    response_time_ms: 180,
    last_seen_at: new Date().toISOString(),
    specialty: "Dispatch, routing, escalation",
  },
  {
    id: "nova",
    name: "Nova",
    role: "Build Engineer",
    status: "focus",
    color: "#8ea4ff",
    avatar_url: null,
    workload: 81,
    throughput: 118,
    accuracy: 96,
    projects_count: 3,
    response_time_ms: 224,
    last_seen_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    specialty: "CI, build systems, releases",
  },
  {
    id: "iris",
    name: "Iris",
    role: "Research Analyst",
    status: "degraded",
    color: "#ff8d73",
    avatar_url: null,
    workload: 57,
    throughput: 97,
    accuracy: 94,
    projects_count: 5,
    response_time_ms: 340,
    last_seen_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    specialty: "Search, synthesis, source QA",
  },
  {
    id: "echo",
    name: "Echo",
    role: "Realtime Monitor",
    status: "online",
    color: "#ffd166",
    avatar_url: null,
    workload: 44,
    throughput: 155,
    accuracy: 99,
    projects_count: 2,
    response_time_ms: 128,
    last_seen_at: new Date(Date.now() - 1000 * 60).toISOString(),
    specialty: "Telemetry and alerting",
  },
];

export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "Apollo",
    summary: "Customer support orchestration with escalations.",
    source: "linear",
    health: "healthy",
    owner_agent_id: "atlas",
    updated_at: new Date().toISOString(),
  },
  {
    id: "p2",
    name: "Beacon",
    summary: "Docs ingestion and semantic retrieval pipeline.",
    source: "github",
    health: "watch",
    owner_agent_id: "iris",
    updated_at: new Date(Date.now() - 1000 * 60 * 24).toISOString(),
  },
  {
    id: "p3",
    name: "Helix",
    summary: "Internal release automation and deploy controls.",
    source: "jira",
    health: "risk",
    owner_agent_id: "nova",
    updated_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
  },
];

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Route multilingual queue to Atlas",
    project_name: "Apollo",
    source: "linear",
    status: "in_progress",
    priority: "urgent",
    assignee_agent_id: "atlas",
    progress: 68,
    due_at: new Date(Date.now() + 1000 * 60 * 60 * 8).toISOString(),
    tags: ["routing", "nlp"],
    updated_at: new Date().toISOString(),
  },
  {
    id: "t2",
    title: "Backfill embeddings for PDF corpus",
    project_name: "Beacon",
    source: "github",
    status: "blocked",
    priority: "high",
    assignee_agent_id: "iris",
    progress: 32,
    due_at: new Date(Date.now() + 1000 * 60 * 60 * 30).toISOString(),
    tags: ["embeddings"],
    updated_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "t3",
    title: "Stabilize staging deploy canary",
    project_name: "Helix",
    source: "jira",
    status: "review",
    priority: "medium",
    assignee_agent_id: "nova",
    progress: 91,
    due_at: null,
    tags: ["release"],
    updated_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "t4",
    title: "Create alert digest export",
    project_name: "Apollo",
    source: "linear",
    status: "backlog",
    priority: "low",
    assignee_agent_id: "echo",
    progress: 8,
    due_at: null,
    tags: ["alerts"],
    updated_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: "t5",
    title: "Promote command palette to prod",
    project_name: "Apollo",
    source: "linear",
    status: "completed",
    priority: "medium",
    assignee_agent_id: "atlas",
    progress: 100,
    due_at: null,
    tags: ["ui"],
    updated_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
  },
];

export const mockActivity: ActivityItem[] = [
  {
    id: "a1",
    agent_id: "atlas",
    project_name: "Apollo",
    title: "Escalation path updated",
    description: "Atlas rerouted 14 priority conversations to tier-2 coverage.",
    level: "success",
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    type: "routing",
  },
  {
    id: "a2",
    agent_id: "iris",
    project_name: "Beacon",
    title: "Retrieval latency spike",
    description: "Vector lookup exceeded threshold for PDF-heavy corpus.",
    level: "warning",
    created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    type: "incident",
  },
  {
    id: "a3",
    agent_id: "nova",
    project_name: "Helix",
    title: "Release candidate built",
    description: "Nova published RC-41 and queued smoke verification.",
    level: "info",
    created_at: new Date(Date.now() - 1000 * 60 * 27).toISOString(),
    type: "build",
  },
  {
    id: "a4",
    agent_id: "echo",
    project_name: null,
    title: "Watchtower recovered",
    description: "Realtime ingestion reconnected after a 90 second gap.",
    level: "success",
    created_at: new Date(Date.now() - 1000 * 60 * 38).toISOString(),
    type: "system",
  },
];

export const mockDocs: DocumentRecord[] = [
  {
    id: "d1",
    title: "Operator Playbook",
    category: "Runbooks",
    type: "Markdown",
    content: "# Operator Playbook\n\n## Dispatch\n\nUse Atlas for queue balancing, Nova for build blockers, and Iris for source-heavy investigations.\n\n## Escalations\n\n1. Mark incidents `critical` when customer impact exceeds 20 active sessions.\n2. Assign Echo when telemetry confidence falls below 90%.\n3. Post summaries to the activity feed within five minutes.\n",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "d2",
    title: "Helix Release Notes",
    category: "Projects",
    type: "Markdown",
    content: "# Helix Release Notes\n\n## RC-41\n\n- Added canary gating for deploy promotion.\n- Hardened rollback checks around config drift.\n- Watch item: staging queue depth remains elevated.\n",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "d3",
    title: "Team Charter",
    category: "Reference",
    type: "Markdown",
    content: "# Team Charter\n\nAtlas Command Center coordinates planning, execution, monitoring, and documentation for autonomous agent work.\n\n## Roles\n\n- **Atlas** owns dispatch and risk decisions.\n- **Nova** owns builds and deployment confidence.\n- **Iris** owns research accuracy and document quality.\n- **Echo** owns observability and alerts.\n",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
  },
];

export const mockIntegrations: IntegrationRecord[] = [
  { id: "i1", name: "Supabase", status: "connected", description: "Primary data and realtime event stream.", latency_ms: 74 },
  { id: "i2", name: "GitHub", status: "connected", description: "Pull requests, issues, and deploy metadata.", latency_ms: 102 },
  { id: "i3", name: "Linear", status: "degraded", description: "Task sync lagging behind target by 2m.", latency_ms: 388 },
  { id: "i4", name: "Slack", status: "disconnected", description: "Notifications paused pending token rotation.", latency_ms: 0 },
];

export const mockCronJobs: CronJob[] = [
  { id: "c1", name: "realtime-healthcheck", schedule: "*/5 * * * *", last_run_at: new Date(Date.now() - 1000 * 60 * 4).toISOString(), next_run_at: new Date(Date.now() + 1000 * 60).toISOString(), status: "healthy" },
  { id: "c2", name: "docs-index-refresh", schedule: "*/30 * * * *", last_run_at: new Date(Date.now() - 1000 * 60 * 11).toISOString(), next_run_at: new Date(Date.now() + 1000 * 60 * 19).toISOString(), status: "healthy" },
  { id: "c3", name: "nightly-snapshot", schedule: "0 2 * * *", last_run_at: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(), next_run_at: new Date(Date.now() + 1000 * 60 * 60 * 8).toISOString(), status: "paused" },
];

export const mockSystemInfo: SystemInfo[] = [
  { id: "s1", region: "us-central-1", version: "2026.03.28", uptime_hours: 418, queue_depth: 23, throughput_per_hour: 1864 },
];
